version: '3.7'
services:
  kubernetes-test-app:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
