apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ quote .Values.name }}
  labels: {{ include "kubernetes-test-app.labels" . | trimSuffix "\n" | indent 2 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- if eq .Values.deployment.linkerdInject "enabled" }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ quote .Values.name }}
          servicePort: {{ .Values.service.port }}
