apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ quote .Values.name }}
  labels: {{ include "kubernetes-test-app.labels" . | trimSuffix "\n" | indent 2 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: {{ quote .Values.name }}
          servicePort: {{ .Values.service.port }}
