apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ quote .Values.name }}
  labels:
    {{- include "kubernetes-test-app.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
  selector:
    {{- include "kubernetes-test-app.selector-labels" . | nindent 4 }}
  type: {{ quote .Values.service.type }}
